Data house.ames0118; 
	set house.ames0118; 
if Pool_QC = "NA" then; 
Pool_QC = .; 
if Fence = "NA" then; 
Fence = .; 
if Fireplace_Qu = "NA" then; 
Fireplace_Qu = .; 
if Garage_Type = "NA" then; 
Garage_Type = .; 
if Garage_Finish = "NA" then; 
Garage_Finish = .; 
if Garage_Qual = "NA" then; 
Garage_Qual = .; 
if Garage_Cond = "NA" then; 
Garage_Cond = .; 
if Misc_Feature = "NA" then; 
Misc_Feature = .; 
if Bsmt_Qual = "NA" then; 
Bsmt_Qual = .; 
if Bsmt_Cond = "NA" then; 
Bsmt_Cond = . ; 
if Bsmt_Exposure = "NA" then; 
Bsmt_Exposure = .; 
if BsmtFin_Type_1 = "NA" then; 
BsmtFin_Type_1 = .; 
if BsmtFin_Type_2 = "NA" then; 
BsmtFin_Type_2 = .; 

run; 